### ISSUE TITLE
Dados dos responsáveis pelo HV Cursos

### ISSUE THREAD

**Issue by rochamatcomp** [saviosg/rm-rf-hvcursos#1]
OXI & HADASSA
Um grupo de várias empresas.

HV CURSOS.
(14) 3367-3178 | (14) 99889-0610 Whatsapp

superintendente@regiaomarilia.com.br

O bot pode vir com o nome HV Cursos e Hadassa Cursos também.

**Comment by saviosg** [comment]
Vi que já entrou em contato com eles. Espero que resolvam esse problema.

Esse Hadassa Cursos vou adicionar ao bot também. Obrigado por avisar.

**Comment by alissonlauffer** [comment]
Aparentemente, eles também estão entrando com o nome de "Hadassa Hv" agora.

**Comment by saviosg** [comment]
> Aparentemente, eles também estão entrando com o nome de "Hadassa Hv" agora.

Adicionado em e939aabd1af1494c75bfb4f1c07cde16b4367b7c
Vou fechar o issue. Caso tenha mais sugestões pode abrir um novo!
