### ISSUE TITLE
Bot falhando

### ISSUE THREAD

**Issue by helioloureiro** [saviosg/rm-rf-hvcursos#2]
Desde ontem percebemos que o bot tem falhado em alguns grupos e permitido o HV Cursos entrar.

Tem alguma coisa nos logs como falha em banir o usuário?

![image](https://user-images.githubusercontent.com/6479951/151186121-dd3ef338-c1c4-4914-b4e7-53dc534a0f9d.png)

![image](https://user-images.githubusercontent.com/6479951/151184932-9d4aabec-9f38-43a4-9df0-62c339750702.png)

**Comment by saviosg** [comment]
A única coisa que o bot faz é verificar se a soma dos campos "first_name" e "last_name" é igual a uma das strings proibidas pelo bot.
Nesse caso ele não deve possuir o caractere espaço, então ao entrar no grupo o bot busca pela string "HVCURSOS" e não encontra.
Isso foi um erro meu quando fiz o bot e não considerei esse caso, mas vou enviar um fix em breve.

**Comment by saviosg** [comment]
O commit 9554bb7f9da9ff4ecd8feedbade0d783a4d3d557 deve resolver o problema. Caso aconteça novamente, pode abrir um novo issue.
